### ISSUE TITLE
Radiant Player doesn't scroblle last song in the playlist.

### ISSUE THREAD

**Issue by Wielosmakowy** [radiant-player/radiant-player-mac#249]
http://i.imgur.com/nUBVH0C.png

**Comment by jacobwgillespie** [comment]
This should be fixed.

**Comment by chrismou** [comment]
This is still an issue, though it extends out a bit further than this. Essentially, it won't scrobble the very last song played before you shut down the player - if you listen to the end of a playlist, wait 10 mins then start a new one, I believe it submits the last song from the previous playlist.

I'm a bit apprehensive about spending time fixing this if we're considering a move to Electron, as the changes will nearly all be to the Obj-C backend and it'll all need rewriting for the Electron build anyway.  Ideally, for current Radiant, we'd split notifySong() into nowPlaying() and scrobble(), submit nowPlaying() at the start of a song, and scrobble() when it ends.

Maybe I'll just sort it. Yeah, I talked myself into it. Reopening the ticket :+1:
