### ISSUE TITLE
Moving window in El Capitan

### ISSUE THREAD

**Issue by leemm** [radiant-player/radiant-player-mac#454]
I know this has apparently been fixed and awaiting release but I've pulled the master branch and built in xcode.  Some things appear to be fixed (UI rendering, Last.fm) but I still can't move the window around.  For some reason it seems to highlight the search bar.  Is there any way around this?

Thanks.

**Comment by leemm** [comment]
Just done so more testing...

If I click anywhere within the display I can't move the window but the window loses focus e.g. click desktop I can then move it.  Very strange.

**Comment by Gbreton76** [comment]
yep, got the same issue here.

**Comment by nelsonwittwer** [comment]
same issue here.

**Comment by mcharmas** [comment]
I have exactly the same issue. Though it was connected with my usage of betterTouchTool but when it is disabled behaviour is the same.

**Comment by jacobwgillespie** [comment]
This is fixed in `master` and should go out this weekend as 1.6

**Comment by leemm** [comment]
@jacobwgillespie Thanks for this but even with 1.6.2 (download and building from the master branch) I'm still unable to move the window unless it looses focus first.  It tries to highlight the test within the search bar.

Also, the UI bug still exists with the frozen display upon minimizing i.e. play a track from an album view, minimise app, open and everything is frozen.

Am I missing something?

**Comment by chrismou** [comment]
Both the issues you've mentioned are still present - we're looking into them.

There was an issue a while ago where moving the window broke completely, which might be what @jacobwgillespie's referring to. Because of the delayed release, it's easy to confuse the 2 issues :-/

**Comment by leemm** [comment]
@chrismou Ah ok.  No problem.  The work around still exists anyway (change window size which triggers the redraw).  Thanks!

**Comment by jacobwgillespie** [comment]
@leemm yeah, the UI bug still exists (#408)

For moving the window, what are the steps to reproduce the bug you're seeing?  I am able to move the window correctly (I think, unless I'm confused) by dragging the title bar...

**Comment by leemm** [comment]
@jacobwgillespie I thought a vid might be better.  http://sendvid.com/9l0gipq2 Radiant Player had just been opened.  I have 3 macs all running El Capitan and the situation is same, click the desktop and it works - once. :)

**Comment by jacobwgillespie** [comment]
Hmm...  And this is on 1.6.2?

**Comment by leemm** [comment]
Yes, the compiled release and building it myself from master.

**Comment by chrismou** [comment]
Actually, I'm not seeing that exact issue. For me, when I drag the window it sometimes just acts like I've let go of the mouse button and stops dragging.  When that happens, the search box usually highlights like in your video.

One thing I've noticed is I only get it when I drag from the lower part of the top bar -ie, the custom bit. If I drag from the very top (ie, where the title bar would usually be) I don't see the issue.

I have no idea if the 2 issues are related

**Comment by leemm** [comment]
Is it worth 'un-closing' this issue?  I've noticed people are still talking about it in other threads.  Thanks!

**Comment by jmcnevin** [comment]
I'm still seeing this on 1.6.2 as well.  I can only initiate a window drag when the window doesn't have focus.

**Comment by jacobwgillespie** [comment]
Anybody who's still experiencing this issue, can you describe your environment?  What software / hardware / OS version, etc.  I'm unable to reproduce, but there must be some common denominator between those of you who can.

**Comment by mcharmas** [comment]
In the newest version it works for me.

**Comment by leemm** [comment]
I've done some more playing and I'm absolutely convinced this is a combination of the lack of a title bar and WAYWindow.

Simply commenting these two lines in the applicationDidFinishLaunching event now allows me to move the window using the standard title bar - not pretty but functional:

```
[self useTallTitleBar];
[ApplicationStyle applyYosemiteVisualEffects:webView window:window appearance:NSAppearanceNameVibrantLight];
```

What's even stranger is that it *also* fixes the second issue i.e. minimising the app to dock while playing.  I no longer get any lockups of the display when it's restored meaning the resizing the window fix is no longer required.

Only tested on the default style, not sure if it still affects the custom ones.

![screen shot 2016-01-07 at 10 28 13](https://cloud.githubusercontent.com/assets/316655/12168342/722bcf5e-b529-11e5-9449-55440640c729.png)
![screen shot 2016-01-07 at 10 01 24](https://cloud.githubusercontent.com/assets/316655/12168347/76b42332-b529-11e5-9876-1d861c86703b.png)

**Comment by chrismou** [comment]
Thanks for looking into this - it's something I've had on my list of todos for a while but not had time to properly look in to.

If this fixes the problem, I'd be happy to go down this route. But it's a bit enough aesthetic change that I'd want a few contributors to chime in with their opinions before it's merged in

If it's as simple as a 2 line change, do you fancy putting a PR in for it?  Just thinking with a PR it'll give us one place to discuss it.  Plus it'll make it easier to test and compare.

**Comment by chrismou** [comment]
OK, so to get the title bar back in the darker themes I had to edit 
ApplicationStyle.m::applyYosemiteVisualEffects too.  The window is *much* more responsive - no lagging at all.

Will also need to unhide the maximize/minimize buttons - thats in AppDelegate.m (326)

@leemm Do you want to sort this or are you happy for me to fix up and put in the PR?  Now we've identified a potential fix I'm keen to get this reviewed ASAP

**Comment by leemm** [comment]
@chrismou I'm fine for you to do the PR if you don't mind.  I'm working on a big project and getting the spare time is a pain at the moment.  Good catch on the themes, I didn't get the chance to check that properly (if at all).

Also, since this only seems to affecting El Capitan maybe it's worth making it a conditional thing via the version number of Mac OS?  Personally I think just having it across the board is better and responsiveness is excellent with the native title bar so maybe just take it out entirely.

**Comment by chrismou** [comment]
Cool, no worries, will try and sort it tonight.  And yeah, I agree, generally I prefer to see stuff like this implemented for all platforms, otherwise it just creates more work down the line.

Either way, this will most likely just turn out to be a stop-gap fix until we can puzzle out why the custom stuff performs so badly when the titlebar is hidden.  Judging by some of the stack overflow questions I've read, it doesn't look like we're the only ones affected and no-one had come up with a reasonable solution yet. One consistent thing is that everyone has noticed it after upgrading to El Capitan.

**Comment by chrismou** [comment]
@jacobwgillespie Out of interest, when you drag the window (and don't see a lag), where are you clicking?  I'm noticing that if I click and hold right at the top of the window (where the titlebar would be if it wasn't hidden) it moves OK for the most part.  The worst of the lag starts when I click any lower than that.

The interesting thing is with the titlebar visible, there's no lag regardless of where you click.  So it's almost as though just having the titlebar transparent is enough to affect drag performance.

**Comment by leemm** [comment]
The thing is the title bar is actually still there but is using a transparency hack to remove visibility.  Perhaps upon dragging it has to continuinely re-draw, applying the hack repeatedly?  I think this might be quite difficult to prove.

Also, it appears the only time I can move the window via the custom titlebar is after it looses focus e.g. clicking the desktop.  My point is the right-click workaround doesn't appear to work on this mac at all.

**Comment by chrismou** [comment]
Even more interesting is I'm watching the profiler and Energy and Memory usage are staying reasonably low despite continuous music playing and loads of clicking around.

It's a bit optimistic to think this will fix #377 and #308 but it's something I'll be keeping an eye on tonight

**Comment by chrismou** [comment]
Now I'm thinking it's probably best if I add this as a preference so people can decide for themselves whether to use a custom or standard title bar.

I'll try and find some time this weekend to finish it off

**Comment by leemm** [comment]
Great idea.  I'd suggest the custom title bar is off by default.  A lot of users are now upgraded to El Capitan and to them it looks like a broken app...

**Comment by jacobwgillespie** [comment]
See #480 for the PR

**Comment by scarroll825** [comment]
I just wanted to note, I was having this issue (unable to move window unless focus was lost) and wanted to test a bit because not everyone was getting the issue. When I disabled the preference for back and forward buttons the issue went away, and I was able to drag the window.

**Comment by skrodal** [comment]
Am experiencing the same issue - only works on lost focus. Disabling preference for back and forward buttons made no diff for me. Also tried complete uninstall/reinstall.

`Radiant 1.6.2` on `El Cap 10.11.3, MacBook Pro`

**Comment by chrismou** [comment]
@scarroll825 @skrodal @jmcnevin 

Pre release build is here: https://github.com/chrismou/radiant-player-mac/releases/tag/1.7.0-pre

Would appreciate having a quick test to see if it fixes the issue for you, if you get some time.  Will probably release this weekend, pending any major issues.

**Comment by skrodal** [comment]
Thanks @chrismou, 

Believe I did a complete removal of previous version (1.6.2) and installed your pre-release. Same issue as before. 

Please note - version of new linked pre-release still says 1.6.2 (not 1.7.0).

**Comment by chrismou** [comment]
Thanks for testting @skrodal!  Now worries about the version, our release process sorts all that out. By keeping it at 1.6.2, you can theoretically keep using my test build, and when the official release it pushed it should still update automatically.

**Comment by chrismou** [comment]
So this should essentially be fixed in 1.7.  If you're still experiencing issues, feel free to open another ticket
