### ISSUE TITLE
UI is jumbled on OS X 10.9.5

### ISSUE THREAD

**Issue by helgammal** [radiant-player/radiant-player-mac#527]
Note the absence of the player buttons [Screenshot1] and the search box overlapped with the header [Screenshot2]. 
Current Radiant Player version: 1.7.4.
OS X version : 10.9.5.
![screenshot1](https://cloud.githubusercontent.com/assets/7671960/14087479/13f0b026-f4df-11e5-8b97-4f53aac9623c.png)
![screenshot2](https://cloud.githubusercontent.com/assets/7671960/14087480/13f0da88-f4df-11e5-85a4-cbe190cb23c3.png)

**Comment by helgammal** [comment]
Addressed by #523. Closing.

**Comment by ccampbell** [comment]
I am using radiant player 1.8.0 and still seeing this on 10.9.5. Is there something special I have to do to get the styles to update?

**Comment by jacobwgillespie** [comment]
@ccampbell for people on Mavericks like yourself, see issue #532.  We have a fix that should go out on the next release.

**Comment by ccampbell** [comment]
Ahh awesome. Thanks!
